### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by codeandcats** [krzkaczor/TypeStrict#11]
I noticed the logo was an exact copy of the Apple bug emoji.

That's cool, it's a gorgeous emoji, but if you're open to it I wanted to propose a slightly customised version of the well known icon.

I basically took the existing logo and slapped some TypeScript blue on it.

<p align="center">
<img src="https://user-images.githubusercontent.com/6035934/56858490-1051a680-69be-11e9-9ecc-aee46fdd0385.png" />
</p>

Then I played around with putting it in a No Smoking/Ghost Buster's style cross.

<p align="center">
<img src="https://user-images.githubusercontent.com/6035934/56858492-18114b00-69be-11e9-9764-ab5a4bfaf9f1.png" />
</p>

I'd be delighted if you chose to use either of these but absolutely no worries if you're not interested. 👍

**Comment by krzkaczor** [comment]
I actually love them 👍 great job! I would love to use those.l but in return I can only offer credits in the readme. Are u fine with it?

**Comment by codeandcats** [comment]
That’s great to hear. No credit necessary.

Cheers 🙂

**Comment by krzkaczor** [comment]
Thanks, merged! I left the credit in readme ;)
