### ISSUE TITLE
Deprecated TsLint Rules

### ISSUE THREAD

**Issue by edieval** [krzkaczor/TypeStrict#13]
Hello guys,

The Ts Lint rules `no-unused-variable` and `no-use-before-declare` are deprecated.

It results with some warning messages: 

`no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.`

`no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.`

Thanks

**Comment by krzkaczor** [comment]
This is related to: https://github.com/krzkaczor/TypeStrict/pull/4
