### ISSUE TITLE
fead: add some more rules

### ISSUE THREAD

**Issue by tomsquest** [krzkaczor/TypeStrict#14]
Some new rules were added to TSLint lately, for example `no-promise-as-boolean` ([changelog](https://github.com/palantir/tslint/releases)), that could be interesting to have in TypeStrict.

**Comment by krzkaczor** [comment]
This is a great rule indeed! I feel like generally `if` statements in typescript could be a lot stricter (for example work only with booleans). 

Anyway, it would be a great addition to `TypeStrict`, feel free to create a PR :)
