### ISSUE TITLE
Broken links in the readme

### ISSUE THREAD

**Issue by rsp** [krzkaczor/TypeStrict#16]
@krzkaczor All of the SonarTS links in the readme are broken (404), see: https://github.com/krzkaczor/TypeStrict#sonarts

The readme in the SonarTS repo says: "TypeScript analysis for SonarQube was migrated to SonarJS plugin. This is a legacy repository used to produce an artifact required for backward compatibility with SonarQube." - see: https://github.com/SonarSource/SonarTS#readme

Is TypeStrict still using the legacy SonarTS or the newer SonarJS? Are there only links broken but the rules are working fine even after the deprecation of SonarTS?

I'll be teaching a TypeScript workshop on Oct 27 and I'd like to recommend TypeStrict so that's why I want to make sure everything is fine. Thanks!

**Comment by krzkaczor** [comment]
TypeStrict still works 😉 i will fix links soon, thanks for noticing it.

**Comment by krzkaczor** [comment]
Thanks! it should be fixed now on `master`.
