### ISSUE TITLE
Branch for v1?

### ISSUE THREAD

**Issue by hmil** [krzkaczor/TypeStrict#20]
Hi,

The move to eslint was kind of disruptive. In hindsight it would have made more sense to create a new package for eslint and keep this one for tslint. But whatever it's done now.

Could you at least keep an active branch for v1 and link to it from the readme of `master`? This way there is a place to track the tslint branch?

Thanks.

**Comment by krzkaczor** [comment]
Hey!

Given that there was no active development happening on v1 I decided not to create such branch 🤷‍♂ buuut I guess it makes sense for people still using tslint. I will leave a readme note about it. 

Note: that eslint version was published as a totally different NPM package so it's not a breaking change.
